### ISSUE TITLE
How to deal with history route mode?

### ISSUE THREAD

**Issue by yllhwa** [EtherDream/web2img#5]
I have a single page website which use history route mode.
In the past I use nginx configuration like:
```nginx
location / {
  try_files $uri $uri/ /index.html;
}
```
to serve all path with index.html.
But how can I deal with history route mode in this project?

**Comment by EtherDream** [comment]
try:

```nginx
error_page            404 = /404.html;

location / {
  try_files $uri $uri/ /404.html;
}
```

**Comment by yllhwa** [comment]
Actually it says: `file not found: /rank`.
I checked the nginx logs and find that the service worker didn't request the server(nginx).

**Comment by EtherDream** [comment]
try `cp index.html 404.html` then pack.

The service worker will use `404.html` to catch unexisted file.

----

src 404.html -> frontend "catch all" (sw)

dst 404.html -> backend "catch all" (nginx)

**Comment by yllhwa** [comment]
all right. It actually works.
Thx for help.
